games_per_eval_matchup: 400
max_ping_interval_seconds_to_track_workers: 30
grpc_port: 2727
num_thread_workers: 3
logs_and_payoff_table_save_key_prefix: population_server/HOSTNAME_pid_PID_DATETIMESTR/
restore_from_payoff_table_key: population_server/sage_pid_18334_09_58_28PM_Apr-27-2020/payoff_tables/payoff_table_36_polices_0_pending_sage_pid_18334_08_19_55PM_May-05-2020.dill
